language: node_js

branches:
  only:
    - master
sudo: true

services:
  - docker

git:
  submodules: false

install:
  - bash bash/install.sh

script:
  - echo "skipping tests"
before_install:
  - openssl aes-256-cbc -K $encrypted_cc51bcff59d0_key -iv $encrypted_cc51bcff59d0_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive


after_success:
  - ssh root@106.14.140.93 "cd citicup && ./setup.sh"

addons:
  ssh_known_hosts: 106.14.140.93
