language: node_js

branches:
  only:
  - master
sudo: true
install:
- bash bash/install.sh

before_install:
- openssl aes-256-cbc -K $encrypted_cc51bcff59d0_key -iv $encrypted_cc51bcff59d0_iv
  -in deploy_rsa.enc -out deploy_rsa -d

after_success:
  - ssh root@106.14.140.93 "./setup.sh"
